import 'package:equatable/equatable.dart';
import 'ai_intent.dart';
import 'citation.dart';
import 'evidence_item.dart';
import 'grounding_status.dart';

/// Semantic operational mode for the AI answer (§27).
enum AIResponseMode {
  directSource,
  evidenceSummary,
  comparative,
  learning,
  appAssistance,
  abstention;

  String get labelArabic {
    switch (this) {
      case AIResponseMode.directSource:
        return 'نص من المصدر الموثق';
      case AIResponseMode.evidenceSummary:
        return 'ملخص مسند بالأدلة';
      case AIResponseMode.comparative:
        return 'عرض الأقوال المتعددة';
      case AIResponseMode.learning:
        return 'شرح تعليمي موثق';
      case AIResponseMode.appAssistance:
        return 'مساعدة في استخدام التطبيق';
      case AIResponseMode.abstention:
        return 'امتناع وتحفظ شرعي';
    }
  }
}

/// Comprehensive, verified response object generated by the safe retrieval engine (§42).
class AIResponse extends Equatable {
  final String requestId;
  final AIResponseMode mode;
  final String answerArabic;
  final List<Citation> citations;
  final List<EvidenceItem> evidenceItems;
  final GroundingStatus groundingStatus;
  final RiskLevel riskLevel;
  final bool isAbstained;
  final String? abstentionReasonArabic;
  final String? scholarReferralArabic;
  final Map<String, dynamic> auditMetadata;

  const AIResponse({
    required this.requestId,
    required this.mode,
    required this.answerArabic,
    this.citations = const [],
    this.evidenceItems = const [],
    required this.groundingStatus,
    required this.riskLevel,
    this.isAbstained = false,
    this.abstentionReasonArabic,
    this.scholarReferralArabic,
    this.auditMetadata = const {},
  });

  @override
  List<Object?> get props => [
        requestId,
        mode,
        answerArabic,
        citations,
        evidenceItems,
        groundingStatus,
        riskLevel,
        isAbstained,
        abstentionReasonArabic,
        scholarReferralArabic,
        auditMetadata,
      ];
}
