import 'package:equatable/equatable.dart';
import '../../../core/time/clock.dart';
import '../domain/ayah_key.dart';
import 'canonical_quran_package.dart';

/// Entry representing a detected Ayah-level diff.
class AyahDiffEntry extends Equatable {
  final AyahKey key;
  final String changeType; // 'ADDED', 'REMOVED', 'TEXT_MUTATION', 'METADATA_DIFF', 'REORDERED'
  final String? oldText;
  final String? newText;
  final String? description;

  const AyahDiffEntry({
    required this.key,
    required this.changeType,
    this.oldText,
    this.newText,
    this.description,
  });

  @override
  List<Object?> get props => [key, changeType, oldText, newText, description];
}

/// Comprehensive report generated by [QuranContentDiffEngine].
class QuranDiffReport extends Equatable {
  final bool hasDifferences;
  final bool hasCriticalTextDifferences;
  final List<AyahDiffEntry> ayahDifferences;
  final List<String> metadataDifferences;
  final DateTime generatedAt;

  const QuranDiffReport({
    required this.hasDifferences,
    required this.hasCriticalTextDifferences,
    required this.ayahDifferences,
    required this.metadataDifferences,
    required this.generatedAt,
  });

  @override
  List<Object?> get props => [
        hasDifferences,
        hasCriticalTextDifferences,
        ayahDifferences,
        metadataDifferences,
        generatedAt,
      ];
}

/// Engine for comparing and auditing differences between two Quran packages (§19).
class QuranContentDiffEngine {
  final Clock _clock;

  const QuranContentDiffEngine({Clock? clock}) : _clock = clock ?? const SystemClock();

  /// Compares old package against new package and outputs a detailed diff report.
  QuranDiffReport comparePackages({
    required CanonicalQuranPackage oldPackage,
    required CanonicalQuranPackage newPackage,
  }) {
    final ayahDiffs = <AyahDiffEntry>[];
    final metadataDiffs = <String>[];
    var hasCriticalTextDiff = false;

    // 1. Edition & Package metadata check
    if (oldPackage.edition.id != newPackage.edition.id) {
      metadataDiffs.add('Edition ID changed from ${oldPackage.edition.id} to ${newPackage.edition.id}');
    }

    // 2. Surah count check
    if (oldPackage.surahs.length != newPackage.surahs.length) {
      metadataDiffs.add('Surah count changed from ${oldPackage.surahs.length} to ${newPackage.surahs.length}');
      hasCriticalTextDiff = true;
    }

    // 3. Sequential order check
    final minLen = oldPackage.ayahs.length < newPackage.ayahs.length
        ? oldPackage.ayahs.length
        : newPackage.ayahs.length;

    for (var i = 0; i < minLen; i++) {
      if (oldPackage.ayahs[i].key != newPackage.ayahs[i].key) {
        ayahDiffs.add(
          AyahDiffEntry(
            key: newPackage.ayahs[i].key,
            changeType: 'REORDERED',
            description: 'Ayah sequence mismatch at index $i: expected ${oldPackage.ayahs[i].key}, got ${newPackage.ayahs[i].key}',
          ),
        );
        hasCriticalTextDiff = true;
      }
    }

    // 4. Index Ayahs by Key for text and metadata diffs
    final oldMap = {for (final a in oldPackage.ayahs) a.key: a};
    final newMap = {for (final a in newPackage.ayahs) a.key: a};

    // Check for removed or modified ayahs
    for (final entry in oldMap.entries) {
      final key = entry.key;
      final oldAyah = entry.value;
      final newAyah = newMap[key];

      if (newAyah == null) {
        ayahDiffs.add(
          AyahDiffEntry(
            key: key,
            changeType: 'REMOVED',
            oldText: oldAyah.textUthmani,
            description: 'Ayah removed in new package',
          ),
        );
        hasCriticalTextDiff = true;
      } else {
        // Compare text
        if (oldAyah.textUthmani != newAyah.textUthmani) {
          ayahDiffs.add(
            AyahDiffEntry(
              key: key,
              changeType: 'TEXT_MUTATION',
              oldText: oldAyah.textUthmani,
              newText: newAyah.textUthmani,
              description: 'Text or diacritic discrepancy detected',
            ),
          );
          hasCriticalTextDiff = true;
        }

        // Compare metadata
        if (oldAyah.pageNumber != newAyah.pageNumber ||
            oldAyah.juzNumber != newAyah.juzNumber ||
            oldAyah.hasSajdah != newAyah.hasSajdah) {
          ayahDiffs.add(
            AyahDiffEntry(
              key: key,
              changeType: 'METADATA_DIFF',
              description: 'Metadata mismatch at $key (Page: ${oldAyah.pageNumber}->${newAyah.pageNumber}, Juz: ${oldAyah.juzNumber}->${newAyah.juzNumber})',
            ),
          );
        }
      }
    }

    // Check for newly added ayahs
    for (final entry in newMap.entries) {
      final key = entry.key;
      if (!oldMap.containsKey(key)) {
        ayahDiffs.add(
          AyahDiffEntry(
            key: key,
            changeType: 'ADDED',
            newText: entry.value.textUthmani,
            description: 'Unexpected new Ayah added in package',
          ),
        );
        hasCriticalTextDiff = true;
      }
    }

    final hasDiffs = ayahDiffs.isNotEmpty || metadataDiffs.isNotEmpty;

    return QuranDiffReport(
      hasDifferences: hasDiffs,
      hasCriticalTextDifferences: hasCriticalTextDiff,
      ayahDifferences: List.unmodifiable(ayahDiffs),
      metadataDifferences: List.unmodifiable(metadataDiffs),
      generatedAt: _clock.nowUtc(),
    );
  }
}
